sudo: false

language: php

services:
 - mongodb
 
cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - LEGACY_DEPS="phpunit/phpunit"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - ALTERNATE_DEPS="phpunit/phpunit"
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
        - EXT_MONGODB=true
    - php: 7
      env:
        - DEPS=locked
        - EXT_MONGODB=true
        - CS_CHECK=true
    - php: 7
      env:
        - DEPS=latest
        - EXT_MONGODB=true
    - php: 7.1
      env:
        - DEPS=lowest
        - EXT_MONGODB=true
    - php: 7.1
      env:
        - DEPS=locked
        - EXT_MONGODB=true
    - php: 7.1
      env:
        - DEPS=latest
        - EXT_MONGODB=true
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
        - EXT_MONGODB=true
  allow_failures:
    - php: hhvm
  
notifications:
  email: false

before_install:
  - if [[ $TEST_COVERAGE != 'true' && "$(php --version | grep xdebug -ci)" -ge 1 ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $EXT_MONGODB == 'true' && $TRAVIS_PHP_VERSION == '7' ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
  - if [[ $EXT_MONGODB == 'true' && $TRAVIS_PHP_VERSION == 'hhvm' ]]; then echo "extension = mongodb.so" >> /etc/hhvm/php.ini ; fi
  - if [[ $EXT_MONGODB != 'true' && $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
  - if [[ $EXT_MONGODB != 'true' && $TRAVIS_PHP_VERSION == 'hhvm' ]]; then echo "extension = mongo.so" >> /etc/hhvm/php.ini ; fi

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $ALTERNATE_DEPS ~= '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $ALTERNATE_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $EXT_MONGODB == 'true' ]]; then composer require --dev $COMPOSER_ARGS alcaeus/mongo-php-adapter ; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then php -m ; fi
  - stty cols 120 && composer show

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
