language: php

services:
 - mongodb
 
php:
  - 5.4
  - 5.5

before_script:
  - pecl install -f mongo-1.4.1
  - composer self-update
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit -c ./test --coverage-clover ./build/logs/clover.xml
  - ./bin/check-cs.sh
  
after_script:
  - php ./vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#apigility-dev"
  email: false
