language: php

services:
 - mongodb
 
php:
  - 5.4
  - 5.5

before_script:
  - pecl install -f mongo-1.4.1
  - composer self-update
  - composer install --dev --prefer-source

script:
  - ./bin/check-cs.sh
  
notifications:
  irc: "irc.freenode.org#apigility-dev"
  email: false
